name: 'CD: Canary'

on:
  push:
    branches: [develop]

jobs:
  gh-release:
    name: 'Release canary build to GitHub'
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [freebsd, linux, netbsd, openbsd]
        arch: [amd64, 386, arm, arm64]
        include:
          - os: darwin
            arch: amd64
          - os: dragonfly
            arch: amd64
          - os: windows
            arch: 386
          - os: windows
            arch: amd64
          - os: solaris
            arch: amd64
          - os: linux
            arch: mips
          - os: linux
            arch: mipsle
          - os: linux
            arch: mips64
          - os: linux
            arch: mips64le
          - os: linux
            arch: ppc64
          - os: linux
            arch: ppc64le
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.CANARY_DEPLOY }}
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.CANARY_DEPLOY }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Git
        env:
          USE_SSH: true
          GIT_USER: ${{ secrets.GH_USER }}

        run: |
          git config --global user.email '${{ secrets.GH_EMAIL }}'
          git config --global user.name '${{ secrets.GH_USER }}'
          mkdir build
          cd ./build
          git init
          git remote add origin git@github.com:${{ secrets.GH_USER }}/tateru.git
          git checkout -b canary-builds
          git pull origin canary-builds
          git branch --set-upstream-to=origin/canary-builds canary-builds
          cd ..

      - name: Build Canary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o build/"$GOOS"-"$GOARCH"-tateru

      - name: Release Canary Build
        env:
          USE_SSH: true
          GIT_USER: ${{ secrets.GH_USER }}
        run: |
          cd ./build
          git add --all

          if [[ $(git diff --stat --staged) != '' ]]; then
            git commit -m "Deploy canary - based on ${{ github.sha }}"
            export failed=0
            (git pull origin canary-builds && git push --set-upstream origin canary-builds) || export failed="1"
            while [ "$failed" = "1" ]
            do
              if (sleep 3 && git pull origin canary-builds && git push --set-upstream origin canary-builds && export success="1"); then
                break
              else
                echo "retrying push..."
              fi
            done
          else
            echo "WD clean"
          fi
