name: 'CD: Canary'

on:
  push:
    branches: [develop]

jobs:
  gh-release:
    name: 'Release canary build to GitHub'
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.CANARY_DEPLOY }}
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.CANARY_DEPLOY }}

      - name: Setup Git
        env:
          USE_SSH: true
          GIT_USER: ${{ secrets.GH_USER }}

        run: |
          git config --global user.email '${{ secrets.GH_EMAIL }}'
          git config --global user.name '${{ secrets.GH_USER }}'

      - name: Build Canary
        run: |
          bash ./gobuild.sh

      - name: Release Canary Build
        env:
          USE_SSH: true
          GIT_USER: ${{ secrets.GH_USER }}
        run: |
          git checkout origin/canary-builds
          git checkout -b canary-builds
          git branch --set-upstream-to=origin/canary-builds

          cd ./build
          git pull
          git add --all

          if [[ $(git diff --stat --staged) != '' ]]; then
            git commit -m "Deploy canary - based on ${{ github.sha }}"
            cd ..
            git subtree push --prefix build origin canary-builds
          else
            echo "WD clean"
          fi
